spring.application.name=shortUrl
#spring.data.mongodb.uri=mongodb://localhost:27017/shorturl

# this is specific to the cloud database i made, subject to change! do not share!!
spring.data.mongodb.uri=mongodb+srv://ndidinwosu:UTh0lbkRnukuvXU2@shortking.0gyef.mongodb.net/?retryWrites=true&w=majority&appName=shortking
spring.data.mongodb.database=shortKingData

security.secret-key=U0cD4LJmDiz/7Lz8oOaQJ7wKnVqz06Pzo3xBk3HRrfE=

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=true

springdoc.show-actuator=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=midnightneon2001@gmail.com
spring.mail.password=mjqppnkymslgddsr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

pom
# google oauth
spring.security.oauth2.client.registration.google.client-id=550088723352-3133b614bjma6ui0v3i53aj75aa3dtiu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=https://www.shortking.dev/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
